python train.py \
    --train_path dataset/train \
    --val_path dataset/val \
    --output_dir experiments/run2 \
    --batch_size 256 \
    --lr 0.0001 \
    --lambda_l1 100 \
    --dropout 0.3 \
    --num_epochs 3 \
    --save_freq 1 \
    --device cuda